version: '3.8'

services:
  coffeeshops:
    image: coffeeshops:latest
    container_name: coffeshop_restapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - coffeeshop-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coffeeshops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffeeshop-network
    ports:
      - "5432:5432"

networks:
  coffeeshop-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
